allowBuilds:
  esbuild: false

autoInstallPeers: false

enableGlobalVirtualStore: false

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true

lockfileIncludeTarballUrl: true

minimumReleaseAgeExclude:
  - "@chalker/*"
  - "@preventive/*"
  - "@rray/*"
