// The small SQL dialect used by the shared store. Parameter values never pass
// through these rewrites; only our own SQL does. Keep aliases case-sensitive.
export function postgresSql(source: string): { sql: string; names: string[] } {
  const names: string[] = []
  let position = 0
  let sql = source.replaceAll('json_each(:contexts)', 'jsonb_array_elements(:contexts::jsonb)')
    .replaceAll(/json_extract\((\w+\.value), '\$\.(\w+)'\)/gu, "($1->>'$2')")
    .replaceAll('json_each(?)', 'jsonb_array_elements_text(?::jsonb)')
    .replaceAll('INSERT OR IGNORE INTO', 'INSERT INTO')
    .replaceAll('CROSS JOIN', 'JOIN')
    .replaceAll(/\binstr\(/gu, 'strpos(')
  // Quoted literals (including ':') are never placeholders or identifiers.
  sql = sql.split(/('(?:''|[^'])*')/u).map((part, i) => i % 2 ? part : part
    .replaceAll(/\?|(?<!:):([a-zA-Z]\w*)/gu, (_match, name: string | undefined) => {
      if (!name) return `$${++position}`
      let index = names.indexOf(name)
      if (index < 0) { index = names.length; names.push(name) }
      return `$${index + 1}`
    })
    .replaceAll(/\b[a-z]+[A-Z]\w*\b/gu, name => `"${name}"`)
  ).join('')
  sql = sql.replaceAll(/(\$\d+) IS NULL/gu, '$1::text IS NULL')
  if (source.includes('INSERT OR IGNORE')) sql += ' ON CONFLICT DO NOTHING'
  return { sql, names }
}

export function postgresSchema(sql: string): string {
  return sql.replaceAll(') STRICT;', ');').replaceAll(/\bINTEGER\b/gu, 'BIGINT')
    .replaceAll(/seq\s+BIGINT PRIMARY KEY/gu, 'seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
}
